### ISSUE TITLE
build fails at stage2

### ISSUE THREAD

**Issue by abigagli** [saarraz/static-print#2]
On macos 10.12.5, native compiler being clang-4.0, the first stage succeeds and xg++ gets successfully built, but then compilation fails during stage2 with the following error:
```
cp-tree.h:1090:5: error: expected unqualified-id before 'static_print'
     static_print;
     ^~~~~~~~~~~~
```
I'm not a gcc wizard, just had a look at cp-tree.h and couldn't see anything in the declaration of static_print so different from the surrounding ones that might justify the error.
Any clue?

**Comment by saarraz** [comment]
Ooh I think I know what the problem is - during stage 2, static_print is a keyword so the above line becomes a syntax error. I'll fix it - thanks!

**Comment by saarraz** [comment]
Fixed! Thanks for the report :)
